{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geoprocessor
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/SantanderMetGroup/geoprocessoR/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f2d33e60519e2bfce5c2fd25bc83d31048089a0588787f9be4421133f6287db0

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - conda-recipe-upstream-validator
  host:
    - r-base
    - r-abind
    - r-gdalutils
    - r-rgdal
    - r-sp <2
    - r-transformer >=1.6.1
  run:
    - r-base
    - r-abind
    - r-gdalutils
    - r-rgdal
    - r-sp <2
    - r-transformer >=1.6.1

test:
  commands:
    - $R -e "library('geoprocessoR')"           # [not win]
    - "\"%R%\" -e \"library('geoprocessoR')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/climate4R
  summary: Geoprocessing tools for climate4R <http://www.meteo.unican.es/climate4R>).
  doc_url: https://github.com/SantanderMetGroup/geoprocessoR
  dev_url: https://github.com/SantanderMetGroup/geoprocessoR
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa
    - mariadlor
